import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ padding: "1rem", backgroundColor: "#f0f0f0" }}>
          <Image src={'/Images/logo.png'} alt="Logo" width={100} height={25}></Image>
        </header>
        <main style={{ margin: "2rem", minHeight: "70vh"}}>
          {children}
        </main>
        <footer style={{backgroundColor:"#f0f0f0", padding: "1rem", textAlign: "center"}}>FoodRush @copyright 2025</footer>
      </body>
    </html>
  );
}
